
= Introduction
Modern Large Language Models (LLMs) have demonstrated remarkable capabilities in pattern recognition and sequence generation. However, they frequently struggle with multi-step algorithmic reasoning and formal logic, often requiring explicit "Chain-of-Thought" (CoT) prompting to perform complex, iterative computations. This reliance on fixed architectural depth and token-level reasoning represents a significant limitation for tasks whose complexity scales independently of the input sequence length, such as mathematical theorem proving and formal verification.

Automated theorem proving requires a model to iteratively transform a *proof state* by applying logical primitives or "tactics." To address this, we introduce the *Thinker* model—a recurrent, latent-based transformer designed to internalize these computational steps within a hidden "thinking" process. Thinker operates at the intersection of three key research frontiers relevant to automated reasoning:

1. *Computational Universality*: Following the tradition of Universal Transformers [1] and Memory-Augmented LLMs [2], Thinker uses recurrence to enable Turing-complete computation. By sharing weights across processing steps, the model learns a single, robust computational primitive that can be applied multiple times to solve problems of varying complexity, analogous to a fixed set of logical rules applied iteratively in a proof.
2. *Latent Bottlenecks & Proof States*: Inspired by the Perceiver [3] and Perceiver AR [4], our model decouples the internal reasoning state (the "proof state") from the raw input through iterative cross-attention. This allows the model to maintain a constant memory footprint while selectively attending to relevant parts of the premises and previous reasoning steps.
3. *Algorithmic Extrapolation for Deep Reasoning*: Unlike CoT methods that externalize reasoning into natural language tokens, Thinker performs its reasoning in a latent space that can be iterated indefinitely. This approach is conceptually similar to "logical extrapolation" techniques [5], where models are trained on simple problems but can solve larger, more complex instances by increasing their computational budget—a critical capability for tackling deep proofs that exceed the complexity of training data.

Our primary contribution is the demonstration of an architecture that not only learns complex algorithmic tasks but also exhibits emergent generalization to higher compute capacities without further training. This provides a potential neural backbone for "thinking" systems capable of the deep, iterative reasoning required for theorem proving.
