= Literature Review

== Recurrent Architectures and Universal Transformers
The quest for computational universality in neural networks began with Recurrent Neural Networks (RNNs) and Long Short-Term Memory (LSTM) networks. External memory was an early complement to this recurrence: Graves et al.'s Neural Turing Machines [9] coupled a recurrent controller with a differentiable, addressable memory bank that the network could read from and write to at every step—a design our persistent memory cache $K_"mem", V_"mem"$ directly inherits, replacing content-based addressing with cross-attention. The introduction of the Transformer architecture by Vaswani et al. (Google Research) [6] revolutionized the field but introduced a fixed architectural depth. Dehghani et al. (Google Brain) [1], in their seminal ICLR 2019 paper, addressed this by applying the same transformer block recurrently. Recent work by Bulatov et al. [7] on Recurrent Memory Transformers (NeurIPS 2022) and the theoretical analysis by Giannou et al. [2] have further refined this, showing that a single looped transformer layer—as detailed in their ICLR 2024 publication—can simulate a Turing-complete computer.

== Latent Bottlenecks and Efficiency
Processing long sequences in transformers is computationally expensive due to self-attention complexity. Jaegle et al. (DeepMind) [3, 4] introduced latent bottlenecks in the Perceiver family, reducing complexity to $O(L dot T)$. This paradigm is essential for theorem proving, where the model must maintain a compact "proof state." More recently, the DeepSeek-AI team [8] proposed Multi-head Latent Attention (MLA) to compress Key-Value caches, achieving over 90% memory reduction.

== Algorithmic Reasoning and Extrapolation
Algorithmic reasoning requires models to generalize beyond their training distribution. Our copy, flip, and roll tasks build on a long line of work on attention as a mechanism for selecting rather than generating: Vinyals et al.'s Pointer Networks [10] showed that a model can produce output sequences by attending back to positions in the input, an idea our cross-attention over the static input cache $K_"in"$ generalizes to arbitrary manipulation and arithmetic tasks rather than combinatorial optimization alone. Bansal, Schwarzschild, and the Maryland team [5, 11] identified the "overthinking" problem in recurrent systems. The "Ca Marche" effect observed in our work aligns with the emergent reasoning capabilities of large-scale models like DeepSeek-R1 [12].

== AI for Formal Theorem Proving
The integration of LLMs with formal proof assistants (Lean, Coq) is a primary frontier. Early systems like GPT-f by Polu and Han (OpenAI) [13], presented at NeurIPS 2020, used transformers to suggest tactics. Modern approaches by Xin et al. (DeepSeek-AI) [14] and Trinh et al. (Google DeepMind) [15] combine large-scale pre-training with Reinforcement Learning. DeepSeekMath [24] introduced Group Relative Policy Optimization (GRPO) to optimize reasoning. Furthermore, systems like TongGeometry by Zhang et al. [31] (Nature Machine Intelligence 2025) demonstrate that guided tree search—a strategy popularized by Silver et al. [16]—can outperform IMO gold medalists.

== Reasoning via Search, Latent Thoughts, and Recurrent Depth
The "OpenAI o1" and "DeepSeek-R1" [12] models have popularized scaling test-time compute via explicit token generation. However, generating thousands of Chain-of-Thought (CoT) tokens incurs substantial memory bandwidth and KV-cache overhead. To address this, recent work explores internalized, continuous latent reasoning. Geiping et al. [37] (NeurIPS 2025 Spotlight) demonstrated that scaling test-time compute via recurrent depth enables language models to solve complex reasoning tasks within latent representations, rivaling models with 10x more parameters. Saunshi et al. [38] (ICLR 2025) proved theoretically that looped transformers possess a distinct inductive bias favoring multi-step reasoning over rote memorization. Fan, Svete, and Lee [39] introduced LOTUS (2026), bridging the gap between latent and explicit CoT via parallel latent supervision. For handling input length variation and dynamic compute allocation, Fan et al. [40] (ICLR 2025) and Jeddi et al. [41] (LoopFormer, ICLR 2026) established elastic-depth mechanisms, while Fu et al. [42] (Think-at-Hard, 2025) mitigated "latent overthinking" via selective recurrence. In parallel, Hao et al. [43] (Coconut, Meta FAIR 2024) showed that feeding continuous latent thoughts enables breadth-first search exploration without discrete token bottlenecks.

== Disentangling Parametric Computation from Associative Memory
Standard Transformers interleave attention with Feed-Forward Networks (FFNs). Mechanistic interpretability research by Geva et al. [47] and Meng et al. [48] (ROME) established that FFN layers act as associative key-value stores for factual knowledge. To scale factual capacity without proportional FLOP increases, recent semi-parametric architectures replace or augment dense FFNs with explicit memory layers. He et al. [45] proposed PEER (2024), routing tokens to over a million tiny expert FFNs via product-key lookup. Berges et al. [44] (Meta FAIR, 2024) scaled this to 128 billion memory parameters in *Memory Layers at Scale*, demonstrating strong empirical scaling laws on factual tasks. Furthermore, hardware-aligned hierarchical sparse attention by Yuan et al. [34] (Native Sparse Attention, ACL 2025 Best Paper) demonstrated that combining coarse-grained block compression with fine-grained selection achieves superior scaling. Thinker builds directly on these insights by exiling factual key-value pairs into a hierarchical indexed memory, restricting the recurrent core to an algorithmic processing unit.

== Local Credit Assignment and Dynamical Stability in Deep Recurrence
Training deep recurrent loops presents acute optimization challenges due to vanishing and exploding gradients. Recent breakthroughs in biologically plausible local learning provide relevant mathematical foundations. Sakana AI [46] introduced Augmented Lagrangian Predictive Coding (PC-ALM, 2026), proving that introducing dual Lagrange multipliers into local layer dynamics forms a Proportional-Integral (PI) feedback controller that achieves ballistic credit propagation across 1000-layer networks without global backpropagation. This control-theoretic framework provides vital stabilization principles for deep unrolled latent recurrence.
